version: '3.8'
services:
  minecraft:
    image: itzg/minecraft-server
    container_name: vapecraft-server
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: "MOHIST"
      VERSION: "1.16.5"
      ENABLE_COMMAND_BLOCK: "TRUE"
    volumes:
      - ./data:/data
      - ./mods:/mods
      - ./plugins:/plugins
    restart: unless-stopped
